### ISSUE TITLE
Column projection

### ISSUE THREAD

**Issue by Antwnis** [51zero/eel-sdk#1]
Should project (slice) particular columns

JdbcSource( ... )
  .project( Range(1..10) )
  .toJdbcSink( .. )

JdbcSource( ... )
  .project( "id","column1","column2")
  .toJdbcSink( .. )

Or re-arrange the order of the columns

JdbcSource( ... )
  .project( "column2","column1","id")
  .toJdbcSink( .. )

**Comment by sksamuel** [comment]
Rearrange would need a full set, or we could have a function that swaps some
