### ISSUE TITLE
filter returns the wrong field

### ISSUE THREAD

**Issue by stheppi** [51zero/eel-sdk#132]
HiveSource(database, "${table}")
        .withColumns("field1", "field2")
       .filter("field2", v=> v== "somevalue")

The v there is for field1 for some reason

**Comment by sksamuel** [comment]
Must be the with columns breaking it because there's tests around filter.

**Comment by sksamuel** [comment]
Are there case differences between field2 in the hive database and field2
in the filter?

**Comment by sksamuel** [comment]
Can you do this:

HiveSource(database, "${table}")
.withColumns("field1", "field2")
.foreach( row => println(row))
.filter("field2", v=> v== "somevalue")

And see if the row is respecting the withColumns. I suspect it not be.

**Comment by stheppi** [comment]
Ok. found the issue. the Frame::filter takes the index out of the schema. However the row (internalrow) respectes the order of the columns defined by withColumns.

all the functions in Frame where outer.schema is used are affected. 
option 1: is get the index with once we have the row (the rows has the columns)
option 2: enhance Frame trait to have def columns: Seq[String]

**Comment by sksamuel** [comment]
We could just update the schema to be in the same order as the columns specified. Then it should all fall together?

**Comment by stheppi** [comment]
or that as option 3
