### ISSUE TITLE
Number of output files in Hivesink depends on threads number

### ISSUE THREAD

**Issue by stheppi** [51zero/eel-sdk#134]
Shouldn't be a link between the number of files created and the threads used to write. We need to add support for creating hdfs files that are rolling based on a threshold or we provide a merge as post processing

**Comment by sksamuel** [comment]
Each thread needs its own file to keep it snappy (you could have a pool of files, but then you just have massive contention as the writing of a single row is about as quick as moving between the locks, but I can test that again).

Eel already supports rolling files based on number of records and / or size. See config options in RollingParquetWriter.

  val MaxRecordsPerFileKey = "eel.parquet.maxRecordsPerFile"
  val MaxFileSizeKey = "eel.parquet.maxFileSize"
  val SkipCrcKey = "eel.parquet.skipCrc"

**Comment by sksamuel** [comment]
If you want a single file, set the ioThreads on hive sink to 1

**Comment by sksamuel** [comment]
1 thread 10m rows is 72s
4 threads, each thread with its own file, 35s
4 threads, synchronizing on a single file, 52s

**Comment by sksamuel** [comment]
I'm going to close this because you can always write with a single thread if you want one file, and the perf improvements are worth keeping a file per thread.
