### ISSUE TITLE
Add lzop support

### ISSUE THREAD

**Issue by Antwnis** [51zero/eel-sdk#136]
Please have a look at this article: http://blog.cloudera.com/blog/2009/11/hadoop-at-twitter-part-1-splittable-lzo-compression/

To compress data with lzo, use lzop. For example to compress and replace all csv files in the current directory:

lzop -U *.csv

eel could have the capability to load and store lzop compressed files

**Comment by sksamuel** [comment]
Support for LZO already exists :) 

Just set eel.parquet.compressionCodec=lzo
