### ISSUE TITLE
Auto-detection of file format

### ISSUE THREAD

**Issue by Antwnis** [51zero/eel-sdk#137]
eel should be able to automatically detect file formats - without the user specifying them ( at least eel-cli )

It should check
- case Parquet =>
- case Orc =>
- case Avro
- case lzop =>
- case xml => 
- case json
- case delimited => case Csv | Osv | Tsv

**Comment by sksamuel** [comment]
Do you mean in hive ?

**Comment by Antwnis** [comment]
No a generic capability i.e.

i have a random file and i want to get out of it a Tsv

`eel-cli convert file-to-automatically-detect-format --output x.tsv`

Of course you can flatten a simple input into a simple output format such as TSV - so complex & nested data should be able to be transformed from Avro <-> Json <-XML->Parquet<-Orc
