### ISSUE TITLE
Collect Parquet statistics (including Hive DBs)

### ISSUE THREAD

**Issue by Antwnis** [51zero/eel-sdk#138]
If not using `Impala` running `select count (*) from xx_table` could require a coffee break to get back results. Even Spark is super slow !

With `eel` we could easily check either a file / or check recursive an entire folder, or an entire hive DB and tables - and if files are Parquet - read super-efficiently and with multiple threads the `stats` from the Parquet footers (!)

If doing that we could easily create a flow

collect-hive-stats ~> etl-ingestion ~> collect-hive-stats ~> display diff of stats !

**Comment by sksamuel** [comment]
I've commented under #139 for this by mistake. What we need now is to know what calculations we can put up as I can give you the full stats for a hive table.

**Comment by Antwnis** [comment]
High level and stats - if run against a table - num of partitions - rows per partitions 
if run against a db - stats per table

in any case summarize - aggregate per table / db to keep track of totals

**Comment by sksamuel** [comment]
Full stats for all partitions now added as part of 1.3.0.
