### ISSUE TITLE
Evaluate Parquet optimizations

### ISSUE THREAD

**Issue by Antwnis** [51zero/eel-sdk#139]
Columnar stuff are taking over big data for a reason. Parquet being a popular one - is a best practise but developers believe that by just storing data into `Parquet` files, they've done the best they could !

That is not quite right. By sorting your data on particular columns possibly things could be
- A lot smaller. More compression if i.e. if repetitive text is ordered alphabetically the repetition would achieve better compression
- A lot faster to read, so you can run quicker your queries

Maybe there is a room for 2-5% efficiency gains or even more. If you imagine checking 5 PBytes parquet files, every **1%** improvement means 50 TB - but actually means **150 TB** (due to HDFS *3 replication) and with current technology hard drives of 5-7.5 TByte / disk, it could lead to some cost savings and an efficiency that the parquet library will never afford to do such checks before serializing into a file, as they are costly experiments required.

Companies like Facebook add ~ 1 PByte / day in columnar data

**Comment by sksamuel** [comment]
Eel can now give you the number of rows per file, the actual file size, and the uncompressed file size. What else do we need?
