### ISSUE TITLE
Pivot capability

### ISSUE THREAD

**Issue by Antwnis** [51zero/eel-sdk#15]
Imagine you have a schema : _quarter - product - sales_ with data

```
("quarter1",  "wine",   100)
("quarter1",  "beer",   220)
("quarter1",  "coffee", 550)
("quarter2",  "coffee", 5)
```

And you want to pivot by _product_ and _sales_ - with newschema = "wine" , "beer" , "coffee" defaultvalue=0 resulting into data

```
quarter      wine     beer   coffee
quarter1      100     220      0
quarter2        0       0      5
```

Also be able to unpivot the data

**Comment by sksamuel** [comment]
I've never really understood pivot tables. It seems you're replacing the
column names with values of a different column, so in this case the type of
drinks are the new column headers. Is it sufficient to just say
frame.pivot(columnName), or do you need to specify two, and if two, why.

**Comment by Antwnis** [comment]
I think this gives some basics analytics capabilities into the lib
One column should be ok

**Comment by garyfrost** [comment]
Simlar to https://issues.apache.org/jira/browse/SPARK-8992 ?

**Comment by sksamuel** [comment]
This might have to live in an algo module as pivot requires all (?) / some (?) data in memory at once.
