### ISSUE TITLE
eel cli to generate a JSON Avro Schema from a Jdbc Query

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#154]
This is probably partly taken care of by the fact eel uses the underlying schema in Hive.

However from a Schema evolution perspective **writers** may want to use an older Avro Schema (providing the new Schema in Hive is backwards compatible with older ones).

This means **writers** don't have to immediately change their software to accommodate Avro Schema upgrades in Hive.

Therefore I think the **HiveSink** should have an optional argument for specifying the write Avro Schema. 

What do you think?

**Comment by sksamuel** [comment]
Do you mean you would want to write from a subset of the schema into a hive table which is a superset? If so, that should work at the moment, if not its a bug. It should fill in missing values for you using defaults.

**Comment by hannesmiller** [comment]
Yes I am talking about writing a subset -  I haven't actually done a test of this - it was more of a question - so I'll take your word on this.
