### ISSUE TITLE
A Sink option to inherit file permissions from the parent HDFS folder

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#157]
A Sink option to inherit file permissions from the parent **HDFS** folder.

This applies to any sink that writes to **HDFS**, e.g. **Hive**, **Hdfs**, **Parquet**, etc…

The problem is when an administrator has granted write permissions at the **group** level for a particular  **HDFS** folder,  then subsequent sub-folders and files created **don’t** inherit the **write** permission because the default **UMASK** policy is usually set to **022** – this means when a new file or folder is created the write permission bit is removed.

One could explicitly pass in a **Filesystem** object with the **UMASK** bit set appropriately for the sink but it would be nice feature to have an option to do this **automagically** on the sink.

_val umask = new FsPermission("002")
...
val permissionToUse:FsPermission = (get permissions from parent folder)
permissionToUse.applyUMask(umask)
...
val fileSystem = FileSystem.get(new Configuration())
val stream = FileSystem.create(fileSystem, path, permissionToUse)_

**Comment by sksamuel** [comment]
In eel 0.98.0 you can do `HiveSource("xxx").withPermission(new FsPermission("700"))` and then all files will use that ACL. It's not quite inherit permissions but you can use it for the same thing.

**Comment by hannesmiller** [comment]
Yeah I guess you could obtain the file permission from parent folder and pass its _FsPermission_ to _withPermisson_.

My only question is why is it on the _HiveSource_ and not on the _HiveSink_ ?

Another option to consider is _HiveSink(blah).withPermissionsFromParent_

**Comment by sksamuel** [comment]
It's on sink not source that's just me getting confused. I'll do the parent
thing too then.

**Comment by hannesmiller** [comment]
That would be cool! 

It probably doesn't sound like a big deal but I have had permission headaches in the past where there are multiple writers belonging to the same functional group and whose permissions are set to 775 on the root folder.
- User1 writes a file under a new partition directory created as 755 - where User1 is the owner
- User2 attempts to write a file to the partitioned directory but cannot because the group perms are read & execute 

Typically UAT & PROD applications are set up with one system account and owner permissions suffice but in DEV this problem rears its ugly head difficult to diagnose with cryptic error messages

**Comment by sksamuel** [comment]
`HiveSink(Database, Table).withIOThreads(4).withInheritPermission(true)`
