### ISSUE TITLE
HiveSink optional arg for partition keys and values 

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#158]
HiveSink to have an optional argument: 

Option[Seq[(String,AnyRef)]]
- The tuple is partitionKey=value
- Should probably be a language agnostic object - easy to use with Java and Scala

The default case of establishing the partition key from the Frame's row still holds :-)

**Comment by sksamuel** [comment]
Can you explain this a bit more ?

**Comment by hannesmiller** [comment]
Actually this is not needed since you told me about adding columns on the fly to the Frame schema
