### ISSUE TITLE
Using multiple Source & Sinks on the same pipeline

### ISSUE THREAD

**Issue by Antwnis** [51zero/eel-sdk#16]
val pipe1 = JdbcSource( ) ....
val pipe2 = JdbcSource( )

val pipe3 = From(_pipe1,pipe2_).join( pipe1.id -> pipe2.customer_id) ...

**Comment by sksamuel** [comment]
You can do this JdbcSource.union(JdbcSource) to append, you want to have
them joined together as a single frame with double width?

**Comment by Antwnis** [comment]
I would expect that you join the data (inner / outer / join) 

and then the new schema becomes the concatenations of the 2 schemas

```
schemaLeft :: schemaRight
```

To achieve that - the column names should be disjoined !
Imagine you have column `id` on left & column `id` on right :-(

You could either have a strict mode - where column name clashes stop the app - or a rename strategy - that i.e. remains the `right` column name that clashes with a column on the `left` into `column-name-right`

**Comment by Antwnis** [comment]
Ah and `always` do `log.warn` on column name clashes !

**Comment by sksamuel** [comment]
It makes no sense to have two columns with same name, and even if you do
left.a and right.a then if you joined again, does it become left.left.a.
Better to err, and make the user rename one of the frames.

**Comment by Antwnis** [comment]
Sure - error it out - it's small data btw :palm_tree:
