### ISSUE TITLE
Kafka zookeepers support

### ISSUE THREAD

**Issue by rofeld** [51zero/eel-sdk#160]
It would be great if it was possible to provide q list of zookeepers instead of or as another option to brokers while reading Kafka stream.

KafkaSourceConfig
case def apply(brokerList: String, consumerGroup: String, autoOffsetReset: String, enableAutoCommit: Boolean): KafkaSourceConfig

brokerList or zookeeperList (new option)

Thank you.
Roman.

**Comment by sksamuel** [comment]
I believe Zookeeper has been dropped from Kafka now.
