### ISSUE TITLE
Provide a *withFieldTypeSpec* & *withTypeSpec* methods for *toFrame*

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#162]
The _withFieldTypeSpec_ method tells _toFrame_ method to convert the field name values to the target type, e.g. from: _decimal(0,38)_ to: _double_
- _withFieldTypeSpec(fieldTypeMap)_
  -- _fieldTypeMap[String,String]_ - where the key is the field name and the value the target type.

The _withTypeSpec(typeMap)_ method automatically converts any field that satisfies the spec:
- _withTypeSpec(typeMap)_
  -- _typeMap[String,String]_ - where the key is the source type and the value the target type

**Comment by sksamuel** [comment]
Did you want this to convert the values as well as the schema?

**Comment by hannesmiller** [comment]
Actually you are right - what I really want is the _schema.showDDL(table)_ to override the hive type - I have already demonstrated the conversion takes place _automagically_  by changing a _decimal(0,38)_ to _double_

**Comment by sksamuel** [comment]
This now works:
`frame.replaceFieldType(FieldType.String, FieldType.Boolean)`
In eel 0.98.0
