### ISSUE TITLE
Additional schema metadata from a source

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#163]
- Need the table name from the JdbcSource and other relevant information like schema/database name if applicable 
- HiveSource schema should also return table name, database, partition info, Hdfs location, Storage Format (parquet, Orc)
- CsvSource schema should give directory location or full path name and any other encoding information - headers, escaping characters etc...

**Comment by sksamuel** [comment]
For CSV Source, the path is what you provide, the headers you can get out via schema() which will return a schema, where each header is a field in the schema.

**Comment by sksamuel** [comment]
Eel 0.97.0 and use `HiveSource(...).spec()`
