### ISSUE TITLE
A File compaction function for EEL

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#164]
Something we have discussed before is having a compact function on the EEL API.

This essentially merges all individual files into a single file.

The reasons for this is 2 fold:

1) Keeps the name node memory compact as each HDFS block occupies around 250 bytes of RAM

2) Fewer memory partitions are created for Spark RDDs/DFs and HDFS native reads - in general this should make read performance more optimal.

There are a number of ways you could approach this:

1) Given that the data is already in HDFS you could use EEL to discover the partitions you desire and create a DF, coalesce to 1 and save

2) Same as the above but use a EEL combination of the HiveSource and the HdfsSink
- Note as part of the process you could remove any empty files. 
- You might consider writing the new file to a  staging _.directory_ and archiving the original directory to _.directory_ on completion, and then renaming the staging directory back to the original name.

**Comment by sksamuel** [comment]
Added
