### ISSUE TITLE
A HBASE Source and Sink for EEL

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#167]
- HBaseSource(namespace, table, colSpec)

-- namespace: the analog for this is Database
-- table: the table name
-- colSpec: comma separated values of column family, column qualifier, column type, e.g.:  _:rowKey:String, cf:col1:string, cf:col2:int_

--- the first field is the name of the row key and therefore doesn't have a column family (empty)
--- the remaining fields specify column family named _cf_ whose columns are _col1_ & _col2_ respectively.

--- Note this should all be compatible with the way Hive maps to HBase table - see http://hortonworks.com/blog/hbase-via-hive-part-1/
- HBaseSink(namespace, table, colSpec)
  -- See _HBaseSource_ for parameter explanation 
- Writing 

-- On the HTable interface there are some _put_ methods - I recommend supporting the one that takes a list of _Put_ objects - this is more efficient than one put at a time, i.e. for every _put_ an RPC is issued to a region server.

-- There are some other optimisation options that are well worth considering to do with I/O but I can't remember off the top of my head - we should come back to that later
- Reading 

-- On the HTable interface there are some _get_ methods - I recommend supporting the one that takes a list of _Get_ objects - this is more efficient than one put at a time, i.e. for every _get_ an RPC is issued to a region server.
- Scanning

Should probably be obtained from a _HBaseReader_ via the _HBaseSource_ ?

I think from a _HTable_ object you can obtain _Scanner_ object whose interface has a plethora of options.

With a scanner you can quickly get back an iterator of row keys that satisfy an input filter which is like a predicate - the predicate filter is pushed down to the region server - client side filtering shouldn't be necessary - you can also filter by partial key, regex and basic ANDs and ORs

That should be enough to get started - there a ton of other things as well like getting the Hive source and sink to understand an external table pointing to HBase - see https://cwiki.apache.org/confluence/display/Hive/HBaseIntegration
- Security

HBase has an admin API - so in Dev you might be able to use the API to create a table, add another column family to an existing table but typically you are restricted from creating another namespace or even being able to list or view other namespace due to permission issues.

I have used the admin API to build a simple CLI tool for creating tables and setting the HBase ACLs - in particular granting the appropriate privileges to special user _impala_ which is required for Impala to access on Hive/Hbase tables.

Checkout:  https://www.tutorialspoint.com/hbase/hbase_admin_api.htm

**Comment by hannesmiller** [comment]
You can assign this one to me.

**Comment by stefanobaghino** [comment]
Wasn't this closed by #365?

**Comment by stefanobaghino** [comment]
(not sure of why it says I unassigned @sksamuel, I only wrote a comment...)

**Comment by sksamuel** [comment]
I was removed from the project, so adding a comment must mean it assigns it to the next person in the list.

**Comment by stefanobaghino** [comment]
Got it, thanks.

**Comment by hannesmiller** [comment]
This should remain closed
