### ISSUE TITLE
Add common Sinks & Sources 

### ISSUE THREAD

**Issue by Antwnis** [51zero/eel-sdk#17]
HBase
Kafka / Queues 
Solr 
MongoDB
Cassandra
Elastic

**Comment by sksamuel** [comment]
What would you do on kafka, because kafka is a streaming source, in that you don't have a set of data, its an ever changing target. You could make it suck in all the messages from a queue from a given offset I suppose.

**Comment by Antwnis** [comment]
suck data in
- until Xo.ooo records fetched
- until timeout = 1.minute reached

also push any source data i.e. from a SQL -> into Json -> kafka topic or avro or whatever :+1:

**Comment by sksamuel** [comment]
Ok cool ideas

**Comment by sksamuel** [comment]
Splitting this up into different issues
