### ISSUE TITLE
Build a Hadoop config object sourced  from a REST service.

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#170]
- Build a Hadoop config object by querying the Cloudera Manager REST Service via their REST API for the site files HDFS, Hive, HBASE, ZooKeeper, etc...
- The properties from these files can be merged into a single object which can subsequently be supplied to the EEL Hive, HDFS, HBase sources and sinks APIs

_Advantages_
- In a development environment like your Windows workstation you can read and write using the Hadoop APIs providing you have all JARs and site files on your classpath as well as  native DLLs in your path.
- Keeping private copies of the Hadoop site files can quickly become stale if servers are moved around or decommissioned - doing this dynamically solves this problem 
- See http://www.cloudera.com/documentation/archive/manager/4-x/4-8-0/Cloudera-Manager-Introduction/cmi_api.html
- Note the CM API requires user and password but for retrieving site files it wasn't required when I tried it against Kerberized clusters in UAT & PROD
- The same approach may work with Ambari - similar to CM but open source and used by Horton Works - see https://cwiki.apache.org/confluence/display/AMBARI/Modify+configurations
- is it too ambitious?
- does this have a place in the EEL framework??

**Comment by sksamuel** [comment]
This is a good idea, if it can be done. Do we have cloudera set up at work, if so, it would be useful for us there too.

**Comment by hannesmiller** [comment]
It can be done...I wrote some experimental code on my last job which used the CM Rest API to drop config files in a location and I was even able to build a Hadoop configuration object on the fly.

Note authentication wasn't required for pulling down just site files

The Rest Service doesn't require autjen

**Comment by sksamuel** [comment]
We have the eel-cloudera module for this now.
