### ISSUE TITLE
Return HDFS partition location & list of files in Hive source and sink

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#171]
- Ideally I would like to inspect the Hive sink at any time to find out the known partitioned directories and associated files during the run - you could just return the absolute path of each file 
- The Hive source could return all known partitions or give it a spec to restrict it to say the last 10 or some other criteria

**Comment by sksamuel** [comment]
Can you give me some details on how you'd want the output specified. Do you want a list of the full partition path (cob=120516/feed=risk) with then a set of files for that ?

**Comment by hannesmiller** [comment]
Perhaps we should have a list (chronological order) of objects to represent this, e.g.:

case class PartitionSpec
(
   location: String,
   fileNames: Seq[String]
) 
- location - the HDFS partition root directory 
- fileNames - a list of file names - up to you if you feel this should be the absolute path

**Comment by sksamuel** [comment]
So for source,

`HiveSource(...).files()`

And for sink

`HdfsSink(...).withFileListener(listener)`

The reason for the listener is that otherwise I'd have to change the signature of the .to method, which is defined on frames, not on hdfs.

**Comment by hannesmiller** [comment]
That's fine with the _withFileListener_ callback on the _HiveSink_ I can discover and collect the information during the write.
