### ISSUE TITLE
CSV source/sink to read & write to HDFS respectively

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#172]
I have a requirement for staging CSV files in HDFS and would like to use the _CsvWriter_ for this.
- _CsvWriter_ constructor argument _path_ is a _java.nio_ type - if the type where URI or string then you could parse out the _scheme_ (file, hdfs) and use the the _HiveSink_ under the hood for scheme HDFS.

**Comment by sksamuel** [comment]
Part of 1.0.0
