### ISSUE TITLE
Map JDBC Decimal and Timestamp to the Parquet & Hive Sinks

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#174]
**JdbcSource -> toFrame -> [Hive|Parquet]Sink** incorrectly maps **Decimals** to Strings and for **TimeStamp** it should convert to a **bigint**.

Note the the **Oracle** jdbc driver yields the type **oracle.sql.TIMESTAMP** which is not derived from **javax.sql.TimeStamp** however setting the sys property **oracle.jdbc.J2EE13Compliant** to **true** should yield a **javax.sql.TimeStamp** type.

**Comment by sksamuel** [comment]
Avro schema doesn't have a bigint, so not sure what to do here, unless we start to use Parquet Schemas directly instead of Avro schemas.

**Comment by hannesmiller** [comment]
Yes in my opinion if we supported Parquet schemas directly then it provides the following benefits:

1. Native support for timestamps, e.g. Int96 
2. Support for other logical types like Decimal which are encoded as fixed byte arrays
3. The Hive SERDE serialises from the native Parquet schema format and not from AVRO schema 
4. Note there are some logical types in Parquet that I believe are not supported in Hive like Date and Time - these types could easily be promoted to Hive Timestamp - IMHO do this when mapping to a Hive/Parquet sink

**Comment by sksamuel** [comment]
Parquet documentation is non existent. Do you know of a list of types in the raw parquet schema.

**Comment by sksamuel** [comment]
This is sorted now.
