### ISSUE TITLE
HiveSink to return write stats at the end of an ETL

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#178]
Currently I use the HiveSink configured with N ioThreads per Hive table.

With this I can tune writes into HDFS to get better throughput however I don't want to be penalised later on READ due to too many small files - the tuning is all trial and error at the moment.

I am thinking of storing some table stats into ElasticSearch for each partition written e.g. the total storage size for all the files for a given partition.

With a history of the stats - I could for example compute the number of ioThreads required based on the current HDFS block size.

- So what would be nice is if the HiveSink could yield the total volume sizes at the end of the Sink run - I could in turn persist it wherever I like.

- In addition I think the Sink writer should set the threads to the MIN of the passed in ioThreads and the number of cores on the machine.

I'm sure I have missed other important criteria - what do you think?

**Comment by sksamuel** [comment]
Done. After writing, call `writeStatus` on the HiveSink to get the file size and records per file.
