### ISSUE TITLE
JdbcSource -> Frame -> ParquetSink maps Numeric JDBC types to String

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#179]
An example is an EEL schema materialized from a *JDBCSource* whose underlying schema may contain decimal numbers:

*Schema(List(Field(sat_deposit_sweep_id,Decimal,false,Precision(38),Scale(0),true,None,List(),false,None))*

A definition like the above should map to *double* as its Hive counterpart.

**Comment by sksamuel** [comment]
Fixed
