### ISSUE TITLE
HiveSource methods select, withProjection, withPredicate not working

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#181]
1)	The *select* method doesn't work specifying columns on the Hive table
2)	The *withProjection* method doesn't work specifying columns on the Hive table
3)	The withPredicate  method only works with columns in the *payload* but not on Hive partition columns which are not part of the *payload*

Here's a snippet of the code code:

HiveSource(database, table)
    // .select("col1", "col2", "col3", "col4") // todo doesn't work bug in EEL
    // .withProjection("col1", "col2", "col3", "col4") // todo doesn't work bug in EEL
    // .withPredicate(Predicate.equals("partition_key", "foo")) // todo we want to hit the partition bug in EEL
    .toFrame(4)
    .toList() // Collect
    .foreach { row => println(row) }

**Comment by sksamuel** [comment]
This turned out to be quite complicated in the end, but now works for all combinations/
