### ISSUE TITLE
EEL 1.1.0-Snapshot HiveSource issues

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#186]
1. *HiveSource.withPredicate(Predicate.gte("exchange_rate", 10))* only supports *Long* types - in fact it should support all number types including strings - if you change *lt*, *lte* and *gte* methods to *java.lang.Number* then auto-boxing should support all types for numbers including *BigDecimal*. Also for strings just use a *Comparable*.

2.  *DataType* trait should have a canonical type name method to return the type *name* excluding the word *Type*, e.g. *StringType* returns  *String*

3. *io.eels.Frame.replaceFieldType* for *DecimalType* should include wildcards for *scale* and *precision* - e.g. I want to map any Decimal type to *Double*. E.g. *.replaceFieldType(DecimalType(), DoubleType)* will not work for every Decimal type permutation.

**Comment by sksamuel** [comment]
All three things are now in 1.1.0-SNAPSHOT
