### ISSUE TITLE
Requesting columns which are uppercase in parquet results in null values returned

### ISSUE THREAD

**Issue by ebar** [51zero/eel-sdk#188]
It seems that eel is applying lowercase to the requested schema when querying parquet files. If the underlying parquet file has an uppercase schema, then null values are returned from the query. 

Perhaps this could be an error condition, or just handled so that the parquet file is queried correctly.

**Comment by sksamuel** [comment]
@hannesmiller can you remember what this was again? Something like parquet created files with upper case schema names (because of JDBC) and then later on eel couldn't find them but spark could? Or vice versa?

**Comment by hannesmiller** [comment]
My workaround for this is to call **Frame.withLowerCaseSchema** when targeting a **HiveSink**.

**Comment by sksamuel** [comment]
Fixed with option to have case insensitive in parquet reads.
