### ISSUE TITLE
Hive dialect for HiveWriter and HiveSource

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#196]
- Essentially means supporting all known Hive Types 
- The following test program shows writing Hive types using the **HiveParquet** serde
- Note the record array below takes **Hadoop** writables - each writable has a **set** method which can be used to avoid massive object creation - use refelection
- Also the **Serde**, **InputFormat**, **OutputFormat** classes can be ascertained from the Hive Meta store and instantiated via reflection.

// Schema (date type currently not supported even though documentation say so)
val tableProperties = new Properties
tableProperties.put(IOConstants.COLUMNS, "myBoolean,myTinyInt,mySmallInt,myInt,myBigInt,myFloat,myDouble,myDecimal,myString,myVarchar,myChar,myTimeStamp,myDate")
tableProperties.put(IOConstants.COLUMNS_TYPES, "boolean,tinyint,smallint,int,bigint,float,double,decimal(10,3),string,varchar(10),char(3),timestamp,date")
tableProperties.put(ParquetOutputFormat.COMPRESSION, CompressionCodecName.SNAPPY.name)

// Create the writer (output format can be ascertained from Hive MetaStore and instantiated via reflection)
val outputFormat = new MapredParquetOutputFormat
val jobConf = new JobConf()
val writer = outputFormat.getHiveRecordWriter(jobConf, path, null, true, tableProperties, null)

// Create the record (SERDE can be ascertained from Hive MetaStore and instantiated via reflection)
val parquetHiveSerDe = new ParquetHiveSerDe
parquetHiveSerDe.initialize(configuration, tableProperties)
val timeStampWritable = new TimestampWritable() // timestamp
timeStampWritable.setTime(System.currentTimeMillis())

val row = new ArrayWritable(classOf[ArrayWritable])
val recordArray = Array[Writable](
	new BooleanWritable(true), // boolean
	new ByteWritable(2), // tinyint
	new ShortWritable(25), // smallint
	new IntWritable(123), // int
	new LongWritable(25L), // bigint
	new FloatWritable(99.99F), // float
	new DoubleWritable(999.99D), // double
	new HiveDecimalWritable(HiveDecimal.create("99.232")), // decimal(10,3)
	new Text("MyString"), // string
	new Text("MyVarchar"), // varchar(10)
	new Text("CHR"), // char(3)
	timeStampWritable, // timestamp
	new DateWritable(new Date(System.currentTimeMillis())) // date
)
row.set(recordArray)

// Write the record
writer.write(parquetHiveSerDe.serialize(row, parquetHiveSerDe.getObjectInspector))

// Close the writer
writer.close(true)

**Comment by sksamuel** [comment]
The latest 1.1 snapshot has full support for native parquet writing, subject to bug reports. I think we can close this now ?

**Comment by hannesmiller** [comment]
Great I will do the following:

- Create Hive tables with decimals and timestamps
- Import data into Hive via EEL
- Test queries in Hive/Spark/Impala
