### ISSUE TITLE
JdbcSource CharType(255) maps to a String for a Hive/Parquet table on showDDL

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#199]
new JdbcSource(() => dataSource.getConnection, query)
val ddl = showDDL(
	s"${hiveSink.database}.${hiveSink.table}",
	fields = source.toFrame.schema.fields,
	tableType = TableType.EXTERNAL_TABLE,
	partitions = partitionKeys,
	location = Some("/mylocation"),
	ifNotExists = true
 )

**Comment by sksamuel** [comment]
So you want the char type to map through to a hive char type.

**Comment by hannesmiller** [comment]
Well **HIVE** has a Char type: **CREATE TABLE foo (bar CHAR(10))**

Not sure if there is a direct mapping for **Parquet**? If not then leave it as **String**

**Comment by sksamuel** [comment]
Parquet only supports String so this mapping is correct.

**Comment by hannesmiller** [comment]
Fair enough
