### ISSUE TITLE
Hive/Parquet sink & sources to write/read custom metadata

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#201]
The following blog mentions adding custom key/value pairs to a Parquet  file:

http://ndolgov.blogspot.co.uk/2016/10/parquet-file-metadata-standard-and.html?m=1

Here's excerpt from the blog:

In addition to the attributes defined by the Parquet format you can also attach arbitrary String key/value pairs to a file. In the write path, your WriteSupport class can override the finalizeWrite() method to return a custom metadata Map. In the read path, you have access to the map in the same place you get access to the file schema. Alternatively, the already mentioned standard API allows you to read custom metadata as well.

It would be nice if the Hive & Parquet sinks & sources could write and read custom metadata respectively:

- For the sinks we could have a with method like: withMetaData(map) - where map is a standard Scala linked hash map - to preserve the insertion order
- For source provide a metaData method to return a map of a map - if applicable, i.e. Only HiveSource backed by Parquet can return this - the key to the outer map would be the path to  the Parquet file and the value would be the metaData for the given file - note to restrict the volume...one should use a predicate or a partition restriction on the HiveSource

What do you think? I can do some further analysis tomorrow.

**Comment by hannesmiller** [comment]
Have you implemented this? What does the API look like??

**Comment by sksamuel** [comment]
.withMetaData and takes a map
