### ISSUE TITLE
Add enum type support

### ISSUE THREAD

**Issue by sksamuel** [51zero/eel-sdk#207]

**Comment by sksamuel** [comment]
What's the impala / hive support like for enums @hannesmiller ?

**Comment by hannesmiller** [comment]
We were using ENUMs extensively for our AVRO Schemas in my last job - they are essentially encoded as strings.

- We used the Schemas to write Parquet files into HDFS
- Created Hive external tables which were readable in a Hive, Spark and Impala
- The Hive column type for ENUM is string 

Does AVRO schema ENUM map to Parquet ENUM? I would have thought so - we need to double check the AvroParquetWriter

**Comment by sksamuel** [comment]
Enums in avro are brilliant. In Parquet not so good.
