### ISSUE TITLE
Partition Strategy for hive sink

### ISSUE THREAD

**Issue by sksamuel** [51zero/eel-sdk#209]
Allow for HiveSink users to specify a strategy to determine how partition names are created.

**Comment by hannesmiller** [comment]
Well you can kind of already do this with the Frame **map** function...the following code snippet uses a **JDBCSource** and adds a new column called **title** depending on the source column **name**.  The Hive table defines **title** as the partition key.

```scala
    // Write to a HiveSink from a JDBCSource
    val query = "SELECT NAME, AGE, SALARY, CREATION_TIME FROM PERSON"
    implicit val hadoopFileSystem = FileSystem.get(new Configuration())
    implicit val hiveMetaStoreClient = new HiveMetaStoreClient(new HiveConf())
    JdbcSource(() => dataSource.getConnection, query)
      .withFetchSize(10)
      .toFrame
      .withLowerCaseSchema
      // Transformation - add title to row
      .map { row => if (row.get("name").toString == "Alice") row.add("title", "Mrs") else row.add("title", "Mr") }
      .to(HiveSink("eel_test", "person").withIOThreads(1).withInheritPermission(true))
```

**Comment by sksamuel** [comment]
This can now be done with the `withPartitionPathStrategy` option on hive sink, and even the `withFilenameStrategy` to decide how the file names are created.
