### ISSUE TITLE
Expose CPU and Record (io) stats via dropwizard metrics

### ISSUE THREAD

**Issue by Antwnis** [51zero/eel-sdk#21]
To make users understand how resources are utilized 'eel' could display [i/o] & [cpu] stats for users to identify - performance measure systems etc

**Comment by sksamuel** [comment]
I'm not even sure how you could do this. How do you know how io bound something is. you'd need to run some system commands I guess.

**Comment by Antwnis** [comment]
In JDK 1.7 you can get system cpu usage and memory usage via OperatingSystemMXBean

```
long    getCommittedVirtualMemorySize()
Returns the amount of virtual memory that is guaranteed to be available to the running process in bytes, or -1 if this operation is not supported.

long    getFreePhysicalMemorySize()
Returns the amount of free physical memory in bytes.

long    getFreeSwapSpaceSize()
Returns the amount of free swap space in bytes.

double  getProcessCpuLoad()
Returns the "recent cpu usage" for the Java Virtual Machine process.

long    getProcessCpuTime()
Returns the CPU time used by the process on which the Java virtual machine is running in nanoseconds.

double  getSystemCpuLoad()
Returns the "recent cpu usage" for the whole system.

long    getTotalPhysicalMemorySize()    
Returns the total amount of physical memory in bytes.

long    getTotalSwapSpaceSize()
Returns the total amount of swap space in bytes.
```

**Comment by sksamuel** [comment]
Yep, but io bounds is what I'd struggle with.

**Comment by sksamuel** [comment]
And if you want CPU stats you can just connect your JMX listener to the process anyway.

**Comment by Antwnis** [comment]
As for `i/o` you could calculate up the memory in terms of physical serialized size

If you `Frame` gets 100.000 records per tick (second) you could just display that
It's interesting to know that rate when pulling i.e. from Kafka / or Cassandra / or ES / or a file / etc

**Comment by sksamuel** [comment]
Yes that's useful. I can add a metrics reporter which we can serialize to
cyber big board.

**Comment by garyfrost** [comment]
Drop wizard?

Gary Frost

**Comment by sksamuel** [comment]
Of course
