### ISSUE TITLE
Extends HDFS Source with file watching capabilities

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#210]
Extends HDFS Source with file watching capabilities

- WithMonitor method to watch a folder in HDFS
- Arguments would be the path to folder, a bit mask of file events or a set of event flags anded together, callback function and  a regular expressions for a file name filter
- On initial invocation the callback is triggered returning  a list of files/directories already in the folder - this useful on a restart - on the underlying FileSystem object checkout list and globStatus methods: http://www.programcreek.com/java-api-examples/index.php?class=org.apache.hadoop.fs.FileSystem&method=globStatus
- Subsequent events will be triggered by file events on the folder like create, modify, close, etc.. checkout the following links on how to do this: dfseventnotifyinputstream - http://stackoverflow.com/questions/29960186/hdfs-file-watcher
- Note there is a small window where you may miss file events on the initial invocation and file events coming in at the same time
- One useful scenario would be when a close event happens on a file...then process it and then move the file to a done folder
- This would be nice as the returned list of file paths could be fed into subsequent file based sources and sinks - Parquet, Orc, CSV respectively

**Comment by sksamuel** [comment]
So we could add a HDFSWatcher class, which does what you want.

**Comment by sksamuel** [comment]
Implemented.
