### ISSUE TITLE
A Kudo Source & Sink for EEL

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#214]
A Kudo Source & Sink for EEL

Kudos is like a hybrid of a RDBMS and a NoSql database.

- The API is similar to HBase and requires a primary key
- Unlike HBase it requires a data model - schema
- Runs on a Hadoop cluster
- It has a columnar storage format with similar features to Parquet
- Currently data can be queried with a beta version of Impala - there may already be some Spark integration?
- There are some early pre-built binaries for CDH but you will need to build your own for (C++) for other distributions 😡
- After building you will need to start up some services, e.g. Master/Slave processes

*Reference material*

- https://kudu.apache.org/overview.html
- https://kudu.apache.org/faq.html
- http://kudu.apache.org/docs/

*Usage*

- JdbcSource -> HiveSink with Kudu dialect
- JdbcSource -> KudoSink
- KudSource -> ParquetSink

**Comment by hannesmiller** [comment]
Closed?

**Comment by sksamuel** [comment]
Yeah it's completed.

**Comment by hannesmiller** [comment]
Sent from my iPhone

On 15 Jan 2017, at 13:17, Stephen Samuel <notifications@github.com<mailto:notifications@github.com>> wrote:

Yeah it's completed.

**Comment by hannesmiller** [comment]
Wow! I need to get it up and running

**Comment by sksamuel** [comment]
Dead easy on Debian.

**Comment by hannesmiller** [comment]
Now that you have the notion of
Primary key for EEL...you should be able to  do HBase source and sink.

- HBase is schema-less and had therefore it would need to be provided on source and sinks
- HBase has the notion of column family (so does Casandra)
