### ISSUE TITLE
Consider combining source and sink into a unified component

### ISSUE THREAD

**Issue by sksamuel** [51zero/eel-sdk#219]

**Comment by hannesmiller** [comment]
Interesting idea but you kind of already have that with Source -> Frame -> Sink?

Interestingly Flume has Source -> Channel -> Sink

Think of channel as a queue and there are different types:

- File Channel - its slow but fully transactional when a source puts events on the queue and the sink takes events off the queue 
- Memory channel - obviously not fully transactional and designed for high througpuyy but there are limits on the size
- Kafka which has pretty goods throughout and supports transactions when used with Flume

A nice feature of Flume is that can buffer up events if you using File or Kafka channels - it's fully transctional, I.e. It will replay the transaction logs on recovery 

- what are you thinking of doing?

**Comment by sksamuel** [comment]
I was just thinking purely from a code level, ie if you want to add a partition to hive, do you do that on a sink, or a source, or a "HiveTable" which is a combined version of the two. But I think its probably best to keep them seperate.
