### ISSUE TITLE
Add support for impala

### ISSUE THREAD

**Issue by Antwnis** [51zero/eel-sdk#23]
By passing in `authmech=3` and user/pass in the jdbc url you can interact with Impala even when Kerberos is enabled

**Comment by sksamuel** [comment]
This can be done by changing the jdbc url ?

**Comment by Antwnis** [comment]
Build two aliases ImpalaSource / ImpalaSink

```
JDBCDriver = "com.cloudera.impala.jdbc3.Driver"
jdbc:impala://host:21050;AuthMech=3;UID=UserName;PWD=Password
```

**Comment by sksamuel** [comment]
Why can't you do JdbcSource("jdbc:impala://host:21050;
AuthMech=3;UID=UserName;PWD=Password") ?

**Comment by sksamuel** [comment]
This is a duplicate of functionality already present in jdbc source
