### ISSUE TITLE
Field class needs ColumnFamily attribute

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#239]
Field class needs ColumnFamily attribute

This is required in preparation for a HBase source and sink and possibly Cassandra.

- Hbase is schema less and is capable of storing any binary values.
- It requires a row key similar to a primary key on Kudu
- **Column Qualifiers** are analogous to columns and belong to a **Column Family**, e.g. **cf1:col1, cf1:col2**
- The only thing that's required when you create a **HBase** table are the column families.
- **Hive** maps HBase coordinates to columns via a table property on the DDL, e.g. **:key, cf1:col1, cf1:col2** - **:key** is the row key and always the first field **cf1:col1** is the column *col1* in the column family *cf1* - checkout **HBaseStorageHandler** for setting up a Hive table - note would be nice to *Hive* sources and sinks to support this dialect.

**Comment by sksamuel** [comment]
We'll add a `ColumnFamilyMapper` that the `HBaseSink` accepts, and uses to map from Field to `ColumnFamily`.
