### ISSUE TITLE
Sources capable of reading multiple files is a good candidate for parallel reads

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#244]
- Say if you have a directory of 100 Parquet/CSV/Avro/Json files you could read them in parallel with a configurable number of threads on their respective sources.
- Also for the **HiveSource** this could improve performance of predicate based queries.

**Comment by sksamuel** [comment]
It does this already actually.

**Comment by hannesmiller** [comment]
Well **ParquetSource** does because it has got **FilePattern** but **CsvSource**, **AvroSource** and **OrcSource** are all capable of reading from **HDFS** but the interface only supports a read on a single file right?

**Comment by hannesmiller** [comment]
Sorry I am assuming that parallel reads for file based sources means each thread reads a separate file from the same **HDFS** folder in parallel - this is not always the case right?

**Comment by sksamuel** [comment]
In HDFS, if there are 10 files in the directory (or subdirectories) then you'll get 10 io threads all reading in parallel.
