### ISSUE TITLE
Provide some text for ORC website?

### ISSUE THREAD

**Issue by omalley** [51zero/eel-sdk#245]
Would you like to provide an Eel paragraph for http://orc.apache.org/docs/adopters.html ?

**Comment by sksamuel** [comment]
@hannesmiller you would know best what to write.

**Comment by hannesmiller** [comment]
Something like this:

[EEL](https://github.com/sksamuel/eel-sdk) is a BigData toolkit API supports reading and writing data for various file formats and storage systems using their respective sources and sinks.

Recently the **Orc** file format (*OrcSource* and *OrcSink*) has been added to suite:

- Nested types such as structs, lists and maps are supported
- Predicate pushdown to efficiently restrict rows returned on the Source
- The *HiveSource* and *HiveSink* supports an *Orc* Dialect
- The *HiveSink* automatically splits data into their respective partition buckets and updates the Hive Metastore if partition keys have been defined
- N I/O Threads can be specified for parallel writes and reads
- EEL is a full Scala 2.11 API
- Coming soon there will be a Java 1.8 edition supporting lambdas and streams

A typical use case would be to extract data from JDBC (Oracle) to Orc files housed in HDFS, e.g.:

```scala
JdbcSource(...)
   .toFrame(...)
   .to( OrcSink(...))
```

Alternatively you could use a  *Hive* table which is backed by an *Orc* file format using the *HiveSink*.

This is only the tip of the ice berg as their various other options and transformation steps one could add.

**Comment by sksamuel** [comment]
If its going on an Orc page we should just mention the orc features.

I've taken yours and adjusted it slightly.

> EEL is a Scala BigData API that supports reading and writing data for various file formats and storage systems including to and from ORC. It is designed as a in-process low level API for manipulating data. Data is lazily streamed from source to sink and using standard Scala operations such as map, flatMap and filter, it is especially suited for ETL style applications. EEL supports Orc predicate and projection pushdowns and correct handles conversions from other formats including complex types such as maps, lists or nested structs. A typical use case would be to extract data from JDBC to Orc files housed in HDFS, or directly into Hive tables backed by an Orc file format.

**Comment by sksamuel** [comment]
@omalley Did you plan to add us to the adopters page Owen? That would be cool.

**Comment by omalley** [comment]
Ok, I pushed the text to the ORC site.

**Comment by sksamuel** [comment]
Thanks @omalley looks good.
