### ISSUE TITLE
Introduce withBatchSize and withCommitSize for the JdbcSink

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#248]
# Proposal

## withBatchSize
To be used with **PreparedStatement.addBatch** statement which buffers up N rows before sending them over the wire, i.e. the opposite to *fetchSize* but has the same effect of making fewer network trips to the database server.  Here's an example:
```java
dbConnection.setAutoCommit(false);//commit transaction manually

String insertTableSQL = "INSERT INTO DBUSER"
			+ "(USER_ID, USERNAME, CREATED_BY, CREATED_DATE) VALUES"
			+ "(?,?,?,?)";
PreparedStatement = dbConnection.prepareStatement(insertTableSQL);

preparedStatement.setInt(1, 101);
preparedStatement.setString(2, "mkyong101");
preparedStatement.setString(3, "system");
preparedStatement.setTimestamp(4, getCurrentTimeStamp());
preparedStatement.addBatch();

preparedStatement.setInt(1, 102);
preparedStatement.setString(2, "mkyong102");
preparedStatement.setString(3, "system");
preparedStatement.setTimestamp(4, getCurrentTimeStamp());
preparedStatement.addBatch();
preparedStatement.executeBatch();
dbConnection.commit();
``` 
- The above adds 2 rows to the batch and them immediately commits.

## withCommitSize
Will issue a **commit** for every N rows - typically this could be used in conjunction with **withBatchSize** and could probably be the same number of rows.  For large data volumes committing at the end of an ETL can sometimes cause the Database Server transaction logs to fill up - committing frequently can reduce this but the downside is you lose a bit of atomicity, e.g.:
```scala
            while (blah) {
              rowCount += 1
              if (rowCount % commitSize== 0) dbConnection.commit()
            }
```

**Comment by sksamuel** [comment]
Added withBatchesPerCommit as well as withBatchSize.
