### ISSUE TITLE
Should we change the case order for some of the Coercers - may improve performance?

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#251]
For the **HBase** source and sink I am making use of the **Coercers**...for some of them I think the first **case** should always be the type you intend to return which is almost like an **no-op**, e.g. for the **LongCoercer** it looks like the following:
```scala
object LongCoercer extends Coercer[Long] {
  override def coerce(input: Any): Long = input match {
    case b: Byte => b
    case i: Int => i
    case l: Long => l
    case s: Short => s
    case s: String => s.toLong
  }
}
````
- If you are calling this millions of times for large volumes then it might add up? e.g. move **case l: Long => l** to the top:
```scala
object LongCoercer extends Coercer[Long] {
  override def coerce(input: Any): Long = input match {
    case l: Long => l
    case b: Byte => b
    case i: Int => i
    case s: Short => s
    case s: String => s.toLong
  }
}
````
- Also look at **IntCoercer**, **FloatCoercer**, **DoubleCoercer**,

**Comment by sksamuel** [comment]
Agreed. Good idea.

**Comment by sksamuel** [comment]
I've adjusted the existing coercers.

**Comment by hannesmiller** [comment]
That's great
