### ISSUE TITLE
New methods required on Frame, e.g. setKey and setFamily

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#257]
For my HBase work I set the key and the column family in the schema fields in the Frame - for now I have some implicits to do this:

```scala
    JdbcSource(() => dataSource.getConnection, query)
      .withFetchSize(10)
      .toFrame
      .withLowerCaseSchema()
      .setKey("name")
      .setFamily(cf = "cf1", fields = "age", "salary", "creation_time")
      .to(HbaseSink("hannes", "test7"))
```

- Could you update the Frame with methods set the key and family using a name of your choice.

**Comment by hannesmiller** [comment]
Note I also have another implicit to build the Frame's schema from a Hive External Table mapped to a HBase table - this is remaining as an implicit as I don't think this method has any business belonging to the Frame.

However if you have any suggestions on how I  could interface this seamlessly would be much appreciated.

**Comment by sksamuel** [comment]
What's the concept of a family on a frame? Does that fit into how a frame is modelled, which is a table?

**Comment by hannesmiller** [comment]
For **Hbase** family is table level concept and is required - **Hbase** is schema-less at the column level - a column family can have as many columns as you like and can change from row to row.

We already have concepts for manipulating the frame's schema at the field level...

- addField, addFieldIfNotExists
- replaceFieldType
- removeField
- updateField (unsupported atm)
- renameField

So if I have a frame coming from JDBC I need to ensure that the key and column families are set before passing it to the **HbaseSink**.

- Currently I achieve this by having my own **implicits** which works fine.
- Note when you map a Hbase table to a Hive table you must specifically map each column using coordinates such as :  ":key,cf1:col1, cf2:col1, cf3:col3" - **key** which is the row key doesn't belong to any column family - I am supporting this as well.

**Comment by sksamuel** [comment]
What I'm saying is a Frame is model of a _table_. How does a key and column sit in with that concept? If HBase doesn't model things as a table, then is it the right fit for the frame abstraction?

**Comment by hannesmiller** [comment]
- Key = Primary Key and I would argue it is a model of table.
- Column Family models HBase and Cassandra tables - you could argue this is additional metadata which I use atm.

**Comment by hannesmiller** [comment]
I could compromise and provide a mapping for **key** and **cf** on the **HBaseSink** - I don't need to do that on the **HbaseSource**.

What do you think?

- Having the **key** on the Field is not really any use unless you say **HBaseSource** -> **KuduSink** - both have concepts of a key.
- For **ColumnFamily** I can just provide mappers in my **HbaseSource** and **HbaseSink** and you don't have to worry about adding that to field.

**Comment by sksamuel** [comment]
Closing this, as we will be adding the column mapper to hbase sink, covered in another issue.
