### ISSUE TITLE
Schema resolution

### ISSUE THREAD

**Issue by sksamuel** [51zero/eel-sdk#259]
If we read from a source we will get a schema. Let's call that schema A.

We then take this frame and write into a source which has its own schema say a hive table which we'll call schema B.

Now what happens if schema A has a field called foo of type String and schema B has a field called foo of type Int. Should we attempt to coerce the String to an Int or leave it to the underlying database to try and sort it out.

This kind of thing could happen when copying from csv to hive where the csv schema is going to be all strings unless overrriden.

@hannesmiller

**Comment by hannesmiller** [comment]
In my mind this is not Schema evolution - when I think evolution it's...what would happen to my current data if I were to add/delete/change a field in my Schema? I.e.  Can I do this without rewriting all the old data with the new schema?

What you are describing is more to do with data transformation...Schema A lacks type information and so you can't cross check it with Schema B types - only by field names and therefore you must coerce the data to the target type - we probably don't need a Schema Inferrer for this use case?

**Comment by sksamuel** [comment]
Schema _resolution_ not evolution.

**Comment by hannesmiller** [comment]
Ha ha - sorry

**Comment by hannesmiller** [comment]
Yes we should attempt to coerce in the CSV case

**Comment by hannesmiller** [comment]
Here's a conundrum...CSV -> HBase

CSV = no type info
Hbase = No Column meta data (dynamic and different from row to row)

**Comment by sksamuel** [comment]
This has been solved by the addition of the coercers.
