### ISSUE TITLE
Add enforceSchema option

### ISSUE THREAD

**Issue by sksamuel** [51zero/eel-sdk#262]

**Comment by hannesmiller** [comment]
Yeah perhaps this should be a method on the **Source** trait?  i.e. enforce the schema based off an AVRO schema.
```scala
CsvSource(path)
  .enforceSchema(AvroSchemaFns.fromAvroSchema(new Schema.Parser().parse(new File("user.avsc"))))
  .to(HiveSink("mydatabase", "myTable"))
```

- Not sure we would want this on the **Sink** trait ?

**Comment by sksamuel** [comment]
On the sink trait, I was thinking if you set schemaEnforce to true, then the hive sink would throw an error if the schema of your inputs do not match the schema in the hive database. Ie, it would not try to evolve the schema in hive for you. So maybe its better to be called withSchemaEvolution(false).

**Comment by sksamuel** [comment]
I think what I'll do is add some way of controlling the writing process in hive, ie a strategy where you can decide how you want to align a row.

**Comment by sksamuel** [comment]
Done, can set an alignment strategy which allows you decide what happens when schemas don't match.
