### ISSUE TITLE
onComplete does not fire on toFrame

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#263]
E.g.

JdbcSource(...)
     .toFrame(myReadListener)
     .to(HiveSink(...),myWriteListener)

- The **onNext** fires for both listeners
- The **onComplete** fires only for **myWriteListener**

**Comment by sksamuel** [comment]
Listeners have been removed on .toFrame (which is now .toDataStream) but this functionality is fixed in that.
