### ISSUE TITLE
The Row should contain an index number within the Frame

### ISSUE THREAD

**Issue by stheppi** [51zero/eel-sdk#266]
Why is this important?
Say we do load from csv and the content of that row is incorrect, when we flag the error we have the row number automatically.
Yes it can be built via a map and adding an index as a new column and before we sink it we can drop it however having this in the framework is better

**Comment by sksamuel** [comment]
The problem is there's no guarantee the number will be the offset in the file, as many sources are async and feed in data from multiple files at once. Maybe you could use the row listener on the source ?
