### ISSUE TITLE
io.eels.component.parquet.ParquetWriterConfig should use ConfigLoader extensions

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#274]
For example I want to turn off compression for Parquet writing and the only way I could get it to work is by creating a **reference.conf** with the following contents:

```
eel.parquet.compressionCodec=UNCOMPRESSED
```

**Comment by sksamuel** [comment]
You want a programmatic option too?

**Comment by hannesmiller** [comment]
Yes that would be cool to have at a per sink level

**Comment by sksamuel** [comment]
I don't understand your original request. What's the error/issue with using eel.parquet.compressionCodec=UNCOMPRESSED

**Comment by hannesmiller** [comment]
I can override the compression property by having my own "reference.conf"  but "env.conf" for example doesn't work?

I have checked this through the debugger and think the WriterConfig class uses just the stars typesafe config without your extensions?

**Comment by hannesmiller** [comment]
Sorry meant standard typesafe config

**Comment by sksamuel** [comment]
I don't want to update eel to use my config extensions library as that's a library I don't mind using on closed source projects, but I don't want to force anyone using eel to also have to use that library.
