### ISSUE TITLE
unexpected blocking of iterator for filtered source with no parts

### ISSUE THREAD

**Issue by jhpoelen** [51zero/eel-sdk#278]
I noticed that when filtering a filePattern to yield no parts, the resulting frame row iterator blocks.

This blocks (v2.1.0-M5) - the code simply hangs and iterator has state ("collecting...")
```
ParquetSource(pathPattern.withFilter((p: Path) => false)).toFrame.rows.iterator.map(row => ...
``` 

So, I introduced the following workaround to prevent the blockage.
```
        val source = ParquetSource(pathPattern.withFilter(pathFilterWithDateRange(ocRequest.added)))
        if (source.parts().nonEmpty)  {
            source.toFrame.rows.iterator.map(row => ...
```

Is this expected behavior?

**Comment by sksamuel** [comment]
It's fixed in the latest snapshots I think, however you should know that the latest snapshots introduces DataStreams to replace Frames (although they're basically the same). Also, there's a race condition in the latest snapshot so I'd wait for 1.2.0-M7.

**Comment by jhpoelen** [comment]
Thanks! Please let me know when next release is available - I'd be happy to verify and close the issue.

**Comment by sksamuel** [comment]
This was fixed now, I've added a test for it. If you try 1.2.0-M10 you should be good.
