### ISSUE TITLE
HttpFS / WebHDFS support

### ISSUE THREAD

**Issue by Antwnis** [51zero/eel-sdk#29]
Sometimes we want to operate over remote hadoop clusters. That can be achieved - through REST calls to HttpFS / WebHDFS.

The only difference between the 2 services above - is that i) they listen on different ports ii) `HttpFS` is minimizing the footprint required to access HDFS, as a single node acts as a "gateway" where `WebHDFS` requires access to all nodes of the cluster 

Introduce capabilities over functionalities:

**File and Directory Operations**
Create and Write to a File
Append to a File
Open and Read a File
Make a Directory
Rename a File/Directory
Delete a File/Directory
Status of a File/Directory
List a Directory

**Other File System Operations**
Get Content Summary of a Directory
Get File Checksum
Get Home Directory
Set Permission
Set Owner
Set Replication Factor
Set Access or Modification Time

**Comment by sksamuel** [comment]
We could add a remote component but the perf would be terrible?
