### ISSUE TITLE
gracefully closing resources for ParquetSource

### ISSUE THREAD

**Issue by jhpoelen** [51zero/eel-sdk#294]
In an attempt to use eel (v1.2.0-M5) in combination with akka-http / akka-streaming, I've create a source shape wrapping eels' ParquetSource into akka-stream SourceShape (see e.g. https://github.com/jhpoelen/effechecka/blob/b06b9b452a7e2d964b6565aa47abf4313f72863a/src/main/scala/effechecka/ParquetSourceShape.scala).

The idea is to stream parquet rows into a http response .

On closing the stream, it seems that the resources for ParquetSource are lingering. This seems to be causing out-of-memory issues on getting multiple requests. 

To free resources, I am calling ```close()``` on the row iterator. Is there a better way to gracefully close/re-use resources related to a ParquetSource?

**Comment by jhpoelen** [comment]
related issue https://github.com/jhpoelen/effechecka/issues/70 .

**Comment by jhpoelen** [comment]
Please note that, for now, I've combined some of the eel features (e.g. file patterns) with a custom implementation of a SourceShape (akka-steam) on top of core parquet library. So, this issue is no longer urgent: am curious to hear your thoughts on eel - akka-stream integration . . .

**Comment by sksamuel** [comment]
I'm going to get eel 1.2.0-M8 out and then tackle your issue, as I think it'll go away as part of those improvements anyway.

**Comment by sksamuel** [comment]
Can you try 1.2.0-M9. In this, the row iterator has been replaced with a subscriber, so should be more like akka streams itself. The resources should be closed off properly.

**Comment by sksamuel** [comment]
1.2.0 final is out. If you need any help to convert your code, I can help.

**Comment by jhpoelen** [comment]
Thanks for letting me know - are you planning to publish a scala 2.11 build to maven repo? For some reason, I only see the 2.12 build.

**Comment by sksamuel** [comment]
The 2.11 is there, http://search.maven.org/#search%7Cga%7C1%7Ceels
I'm using it myself :)

**Comment by jhpoelen** [comment]
Oops , my bad - I didn't realize that eel-components no longer exists in 1.2.0 version. I tried to upgrade, and appears to breaks some of the usage related to eel FilePattern in https://github.com/jhpoelen/effechecka/blob/209eb450ee118a72da19a35e0ee0c6cb917aa15f/src/main/scala/effechecka/ParquetReaderSourceShape.scala#L23 .

**Comment by sksamuel** [comment]
Can you be more detailed on what's broken there as it's not clear to me
sorry.

**Comment by sksamuel** [comment]
I think what you could do now, is create a `ParquetSource` and use the iterator on that.

so, something like,

```scala
  setHandler(out, new OutHandler {

    val iterator = ParquetSource("filename").toDataStream().iterator

    override def onPull(): Unit = {
      if (iterator.hasNext)
        push(out, iterator.next)
      else {
        complete(out)
      }
    }
  }
```

I've not tested this and I'm not sure on how the out/out handler works. But if you use the iterator on the `DataStream` then once the iterator is empty, you could close down the out stream. The hasNext method will block until a row is available. If your parquet files are quite small, then you could use `.collect` instead of `.iterator` which would bring back a `Vector[Row]`.

If akka has something a bit more push based, then you could use `subscribe` on the DataStream and then it would be a bit nicer.

**Comment by sksamuel** [comment]
Actually ignore that, because iterator won't expose a close method, it will rely on you exhausting the stream, which isn't great. The other methods will close properly, and `subscribe` which is the main thing now, will always properly terminate the source in cases of an error.

**Comment by jhpoelen** [comment]
No worries! Closing issue for now and continuing to use your library for FilePattern and serialization and using parquet lib directly with akka-stream. Thanks for sharing your insights.
