### ISSUE TITLE
Example to read and write array of structs to/from a parquet file

### ISSUE THREAD

**Issue by satyavikas** [51zero/eel-sdk#332]
Hello,

Can you please point me to a working example of reading and writing an array of structs to/from a parquet file. I'm trying to workout an example from the documentation ( PERSON DETAILS, PHONE NUMBERS ) but instead of Array of Strings ( ArrayType.Strings) I want to use Array of Structs. 

To give some background, in the "person-details" example instead of using the phone-numbers I'm trying to extend the example adding a new column called "friends" which is an array of structtype "friend".

Problem: I'm able to write/read to/from a parquet file but I see "null" everywhere for the friends column. Please kindly take a look at the code below and correct me if I'm doing anything wrong.
My libraryDependecies are:

**"org.apache.hadoop" % "hadoop-common" % "2.7.3",
  "org.apache.hadoop" % "hadoop-hdfs" % "2.7.3",
  "io.eels" % "eel-core_2.12" % "1.2.3"**

Code:

```
import org.apache.hadoop.conf.Configuration
import org.apache.hadoop.fs.FileSystem
import org.apache.hadoop.fs.Path
import io.eels.component.parquet._
import io.eels.datastream.DataStream
import io.eels.schema._
import java.sql.Timestamp

object ReadParquetEEL {

  def readParquet(filepath: String): Unit = {

    val parquetFilePath = new Path(filepath)
    implicit val hadoopConfiguration = new Configuration()
    implicit val hadoopFileSystem = FileSystem.get(hadoopConfiguration)
    val rows = ParquetSource(parquetFilePath).toDataStream().collect
    rows.foreach(row => println(row))
  }

  def main(args: Array[String]): Unit = {

    val parquetFilePath = new Path("file:///d1/data/clasp/person2.parquet")
    implicit val hadoopConfiguration = new Configuration()
    implicit val hadoopFileSystem = FileSystem.get(hadoopConfiguration)

    val friendStruct = Field.createStructField("FRIEND",
      Seq(
        Field("NAME", StringType),
        Field("AGE", IntType.Signed)
      )
    )
    val personDetailsStruct = Field.createStructField("PERSON_DETAILS",
      Seq(
        Field("NAME", StringType),
        Field("AGE", IntType.Signed),
        Field("SALARY", DecimalType(Precision(38), Scale(5))),
        Field("CREATION_TIME", TimestampMillisType)
      )
    )
    val friendType = StructType(friendStruct)
    val schema = StructType(personDetailsStruct, Field("FRIENDS", ArrayType(friendType), nullable = false))

    val friends = Vector(
      Vector(Vector("John", 25)),
      Vector(Vector("Adam", 26)),
      Vector(Vector("Steven", 27))
    )

    val rows = Vector(
      Vector(Vector("Fred", 50, BigDecimal("50000.99000"), new Timestamp(System.currentTimeMillis())), friends))

    // Writing
    try {
      DataStream.fromValues(schema, rows).to(ParquetSink(parquetFilePath))
    }
    catch {
      case e: Exception => e.printStackTrace()
    }
    // Reading
    try {
      readParquet("file:///d1/data/clasp/person2.parquet")
    }
    catch {
      case e: Exception => e.printStackTrace()
    }
  }
}
```

I'm trying to access a local parquet file by qualifying it with the **file: scheme**.

Here is the output when I read the file:
[PERSON_DETAILS = WrappedArray(Fred, 50, 50000.99000, 2017-07-26 15:51:17.222),FRIENDS = Vector(WrappedArray(WrappedArray(null, null)), WrappedArray(WrappedArray(null, null)), WrappedArray(WrappedArray(null, null)))]

Thanks for your time.

**Comment by sksamuel** [comment]
I get the same behaviour so it must be a bug in the parquet reader or writer.

**Comment by sksamuel** [comment]
The bug is in the parquet writer. I'll fix it very soon.

**Comment by satyavikas** [comment]
Sure. Thanks for the response. 

EDIT:
Can it be the case that there might be an issue in the parquet reader too ? I ask this because when I try to read parquet files that are generated by some other technology ( for eg: spark, hive etc etc ), I see the same behavior. 

Thanks.

**Comment by sksamuel** [comment]
You are right, the bug is in the reader, not the writer.

**Comment by sksamuel** [comment]
I've fixed the error in master. I'll apply it to 1.2 and do another release.

**Comment by satyavikas** [comment]
Hello,

Thanks for the response. When can the release be expected?

**Comment by sksamuel** [comment]
Next hour.

**Comment by sksamuel** [comment]
Ok 1.2.4 is released.

**Comment by sksamuel** [comment]
@satyavikas can you confirm this can be closed.

**Comment by satyavikas** [comment]
Hello Samuel,

Sorry I couldn't report back on time. The tool works as expected at-least as per my tests.

Thanks for fixing this.

**Comment by sksamuel** [comment]
Cool, closing.
