### ISSUE TITLE
CsvSource parser configuration

### ISSUE THREAD

**Issue by gh-osama** [51zero/eel-sdk#357]
While reading CsvSource files, I get `Array out of Bounds` error on rows with data longer than the default column width set to 4096:

```13:14:24.086 [pool-2-thread-1] ERROR io.eels.datastream.DataStreamSource - Error reading part 0
com.univocity.parsers.common.TextParsingException: Length of parsed input (4097) exceeds the maximum number of characters defined in your parser settings (4096). 
Hint: Number of characters processed may have exceeded limit of 4096 characters per column. Use settings.setMaxCharsPerColumn(int) to define the maximum number of characters a column can have
```

How can the csv parser configuration be changed to allow for longer column widths?

**Comment by sksamuel** [comment]
I can add that option to the CSV Source.

**Comment by sksamuel** [comment]
Fixed in master. Which version are you using?

**Comment by gh-osama** [comment]
Thanks for doing this! I just updated my deps to latest master.

**Comment by sksamuel** [comment]
Great hope it works.

**Comment by gh-osama** [comment]
Let me know if there are issues/docs with `help wanted`; I am using eel-parquet inside an AWS Lambda container w/ Scala ofc ;) and it works so well!

**Comment by sksamuel** [comment]
I wrote eel initially for use at Barclays and then Deutsche Bank. So it's nice to hear of other users outside of those two banks. We might call you up for help :)
