### ISSUE TITLE
`iterator` in DataStream never submits to the executor

### ISSUE THREAD

**Issue by emilypi** [51zero/eel-sdk#364]
The offending code:

```scala

  def iterator: Iterator[Row] = {
    val queue = new LinkedBlockingQueue[Row]()
    val executor = Executors.newSingleThreadExecutor()
    self.subscribe(new Subscriber[Seq[Row]] {
      override def next(t: Seq[Row]): Unit = t.foreach(queue.put)
      override def completed(): Unit = queue.put(Row.SentinelSingle)
      override def error(t: Throwable): Unit = queue.put(Row.SentinelSingle)
      override def subscribed(c: Subscription): Unit = ()
    })
    executor.shutdown()
    BlockingQueueConcurrentIterator(queue, Row.SentinelSingle)
  }

```

https://github.com/51zero/eel-sdk/blob/master/eel-core/src/main/scala/io/eels/datastream/DataStream.scala#L285

**Comment by hannesmiller** [comment]
Hi Emily,

Thank you for the post.

Can you tell us the EEL version you are using?  And the Sources and Sinks?

We will be taking a look at this week and get back ASAP.

Thanks and Regards,
Hannes

**Comment by emilypi** [comment]
@hannesmiller 

You didn't read the post. I provided a link to the code. It's in your `master` branch, and has been as of October.

**Comment by garyfrost** [comment]
Hi @emilypi we'll look into this right away, do you have (or could you create) a failing test case that demonstrates the error.

BTW you are very welcome to create a PR with a fix if you are interested in doing so.

**Comment by emilypi** [comment]
@garyfrost Appreciated, and I will next time. it's a simple fix, just submit what you want to the executor, because right now it's just spinning up a new ExecutorService and closing it while doing all of the work serially.
