### ISSUE TITLE
support for mapping ArrayTypes to correct (db-vendor-specific) jdbc array types 

### ISSUE THREAD

**Issue by FloWi** [51zero/eel-sdk#376]
I've encountered a bug in the jdbc-layer of eel. 
If I have an array-type in the schema eel deserializes it as a `scala.collection.immutable.Vector[T]`. 

When you try to insert with such an ArrayType field, the preparedStatement crashes stating that the given type (`Vector[T]`) is not supported.

JDBC doesn't support collection-types, you can only store db-vendor-specific sql-arrays. You can get this form the jdbc.connection with `conn.createArrayOf()`.

I edited the JdbcInserter to make it work with my string-collection (for my example-usecase).

```scala
  def insertBatch(batch: Seq[Row]): Unit = {
    val stmt = conn.prepareStatement(dialect.insertQuery(schema, table))
    try {
      batch.foreach { row =>
        row.values.zipWithIndex.foreach { case (value, k) =>
          val isStringArray = schema.field(k).dataType == ArrayType(StringType)

          if (isStringArray) {
            val stringArray = value.asInstanceOf[Vector[String]]

            val sqlArray = conn.createArrayOf("VARCHAR", stringArray.toArray)

            stmt.setObject(k + 1, sqlArray)
          } else {
            stmt.setObject(k + 1, value)
          }
        }
        stmt.addBatch()
      }
//...
```

Do you have an idea how to generalize that code?

spark-sql does it like this in `JdbcUtils`.

```scala
    case ArrayType(et, _) =>
      // remove type length parameters from end of type name
      val typeName = getJdbcType(et, dialect).databaseTypeDefinition
        .toLowerCase(Locale.ROOT).split("\\(")(0)
      (stmt: PreparedStatement, row: Row, pos: Int) =>
        val array = conn.createArrayOf(
          typeName,
          row.getSeq[AnyRef](pos).toArray)
        stmt.setArray(pos + 1, array)

```

I think I have some time tomorrow to take a look into it. It'd be great if you could point me in the right direction like
- can you point me to a running testcase that writes data into a database-table that I can extend?
- how to check if the value is an `ArrayType` (without explicitly writing e.g. `ArrayType(String)`)
- how to get the jdbc-types of the elements of the collection

**Comment by FloWi** [comment]
ah, I've found a the `io.eels.component.jdbc.JdbcSinkTest`

**Comment by hannesmiller** [comment]
@FloWi I responded on Gitter

**Comment by hannesmiller** [comment]
@FloWi well you can could pattern match the ArrayType, e.g.:

```
schema.field(k).dataType match {
  case ArrayType(eType) => blah
  ...
 }

**Comment by hannesmiller** [comment]
Or simply ignore the element type and just always use an *AnyRef* like the spark implementation is doing - though it does look Spark is doing something with the element type and the dialect.

**Comment by FloWi** [comment]
Got it working and wrote a testcase for the h2 database. Also works on postgres (tested manually with a string-array-column)
