### ISSUE TITLE
unresolved dependencies when running sbt package

### ISSUE THREAD

**Issue by danielhaviv** [51zero/eel-sdk#383]
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/net.virtual-void/sbt-dependency-graph/scala_2.12/sbt_1.0/0.8.2/ivys/ivy.xml
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.sbt#sbt-pgp;0.8.3: not found
[warn] 	:: com.github.gseitz#sbt-release;1.0.0: not found
[warn] 	:: net.virtual-void#sbt-dependency-graph;0.8.2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.typesafe.sbt:sbt-pgp:0.8.3 (scalaVersion=2.12, sbtVersion=1.0)
[warn] 		com.github.gseitz:sbt-release:1.0.0 (scalaVersion=2.12, sbtVersion=1.0)
[warn] 		net.virtual-void:sbt-dependency-graph:0.8.2 (scalaVersion=2.12, sbtVersion=1.0)
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.typesafe.sbt:sbt-pgp:0.8.3 (scalaVersion=2.12, sbtVersion=1.0) (/Users/dhaviv/projects/eel-sdk/project/plugins.sbt#L3-4)
[warn] 		  +- default:project_2.12:0.1.0-SNAPSHOT
[warn] 		com.github.gseitz:sbt-release:1.0.0 (scalaVersion=2.12, sbtVersion=1.0) (/Users/dhaviv/projects/eel-sdk/project/plugins.sbt#L5-6)
[warn] 		  +- default:project_2.12:0.1.0-SNAPSHOT
[warn] 		net.virtual-void:sbt-dependency-graph:0.8.2 (scalaVersion=2.12, sbtVersion=1.0) (/Users/dhaviv/projects/eel-sdk/project/plugins.sbt#L7-8)
[warn] 		  +- default:project_2.12:0.1.0-SNAPSHOT
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.sbt#sbt-pgp;0.8.3: not found
[error] unresolved dependency: com.github.gseitz#sbt-release;1.0.0: not found
[error] unresolved dependency: net.virtual-void#sbt-dependency-graph;0.8.2: not found

**Comment by mycaule** [comment]
I think you should try to upgrade your sbt version.

Here is the combination I used in `build.sbt`
```
  scalaVersion := "2.12.6",
  sbtVersion := "1.1.4", 
  eelVersion = "1.2.4"
  ...
  "io.eels" %% "eel-core" % eelVersion,
```

For a complete list of version compatibilities https://mvnrepository.com/artifact/io.eels/eel-core

**Comment by danielhaviv** [comment]
Thanks.
Do I need to create build.sbt myself (there isn't one as part of the project)?

**Comment by mycaule** [comment]
What file have you listed your dependencies in ?
May be you have `build.scala` ?
