### ISSUE TITLE
JDK 1.7 - Unrecognized VM option 'MaxMetaspaceSize=1G'     

### ISSUE THREAD

**Issue by Antwnis** [51zero/eel-sdk#58]
`sbt clean                                                                                             
Unrecognized VM option 'MaxMetaspaceSize=1G'                                                                                                     
Error: Could not create the Java Virtual Machine.                                                                                                
Error: A fatal exception has occurred. Program will exit.`

I get that with java version "1.7.0_95"

Had to remove `-J-XX:MaxMetaspaceSize=1G` from .sbtopts

**Comment by sksamuel** [comment]
1.7 was end of life in April 2015 but I'll make sure we support it :
