### ISSUE TITLE
Consider renaming frame to stream

### ISSUE THREAD

**Issue by sksamuel** [51zero/eel-sdk#62]

**Comment by sksamuel** [comment]
What do you think @stheppi  @garyfrost

**Comment by sksamuel** [comment]
@Antwnis too

**Comment by stheppi** [comment]
Won't be confusing with the collection Stream?

**Comment by sksamuel** [comment]
Yes. But no one uses them. Open to other names :) or not changing it.

**Comment by stheppi** [comment]
Stream it is then 😊

**Comment by sksamuel** [comment]
You think its better than Frame? Frame is growing on me...

**Comment by Antwnis** [comment]
Let's grow the entropy in this thread :8ball: 

Let's call them `MiniFrame` 

So we have `DataFrame` on spark - or `MiniFrame` on eel :+1:

**Comment by Antwnis** [comment]
And we define `MiniFrame` as anything from a few records up to a few 10's of millions or records

**Comment by sksamuel** [comment]
Ok so MiniFrame and Stream currently.

**Comment by sksamuel** [comment]
Dataset is another

Or River.
