### ISSUE TITLE
Add synthetic data generator module `eel-generate`

### ISSUE THREAD

**Issue by Antwnis** [51zero/eel-sdk#74]
Sometimes you don't have data to begin with. You want to simulate a few SQL tables, and you want to easily generate some synthetic data - i.e. maybe just a few thousand lines

Eel could generate for example a table with

`eel-generate --lines 10000 --format=[ csv | json | xml | avro ] --column1=[columnname],[type] --column2=....  > new_dataset.json`

Example

`--column1=surname,type=string[40]`

would generate random strings 40 chars in length

`--column1=id,type=index`

Would generate auto-incremental Long nums starting from 1 ( or index[4000] ) to start from 4000

**Comment by sksamuel** [comment]
I think this is out of scope now.
